In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()


In [5]:
corpus=[
    'This is first document.',
    'This is second document.',
    'This is third document.',
]

In [7]:
x = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())  
print(x.toarray())  

['document' 'first' 'is' 'second' 'third' 'this']
[[0.41285857 0.69903033 0.41285857 0.         0.         0.41285857]
 [0.41285857 0.         0.41285857 0.69903033 0.         0.41285857]
 [0.41285857 0.         0.41285857 0.         0.69903033 0.41285857]]


In [10]:
df=pd.read_csv('train.csv')
df.head()

textID                                               text  \
0  cb774db0d1                I`d have responded, if I were going   
1  549e992a42      Sooo SAD I will miss you here in San Diego!!!   
2  088c60f138                          my boss is bullying me...   
3  9642c003ef                     what interview! leave me alone   
4  358bd9e861   Sons of ****, why couldn`t they put them on t...   

                         selected_text sentiment  
0  I`d have responded, if I were going   neutral  
1                             Sooo SAD  negative  
2                          bullying me  negative  
3                       leave me alone  negative  
4                        Sons of ****,  negative

In [ ]:
df["text"]=df["text"].fillna("")
vectorizer=IfidfVectorizer(max_feature=1000)
vectorizer.fit(df['text']
tf_idf_data_fra